// Copyright 2025 Buf Technologies, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package generator

import (
	"fmt"
	"math"
	"path/filepath"
	"strconv"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/reflect/protoreflect"
	"google.golang.org/protobuf/types/descriptorpb"

	"buf.build/go/hyperpb/internal/gencode/printer"
	"buf.build/go/hyperpb/internal/gencode/wkt"
)

type Generator struct {
	// Set of messages whose identifiers' paths have been updated.
	updated map[*protogen.Message]struct{}
}

func (g *Generator) Generate(pl *protogen.Plugin, subdir string, f *protogen.File) {
	dir := filepath.Dir(f.GeneratedFilenamePrefix)
	base := filepath.Base(f.GeneratedFilenamePrefix)
	path := filepath.Join(dir, subdir, base+".pb.go")

	origPath := f.GoImportPath
	g.updatePkg(f, subdir)

	fg := &file{
		Printer:  printer.NewPrinter(pl.NewGeneratedFile(path, f.GoImportPath)),
		pl:       pl,
		file:     f,
		ordinary: origPath,
		subdir:   subdir,
	}
	fg.Run()
}

func (g *Generator) updatePkg(f *protogen.File, subdir string) {
	f.GoImportPath += protogen.GoImportPath("/" + subdir)
	for _, m := range f.Messages {
		g.updateMessagePkg(m, subdir)
	}
}

func (g *Generator) updateMessagePkg(m *protogen.Message, subdir string) {
	if _, ok := g.updated[m]; ok {
		return
	}
	if g.updated == nil {
		g.updated = make(map[*protogen.Message]struct{})
	}

	g.updated[m] = struct{}{}
	m.GoIdent.GoImportPath += protogen.GoImportPath("/" + subdir)

	for _, m := range m.Messages {
		g.updateMessagePkg(m, subdir)
	}
}

type file struct {
	*printer.Printer
	pl       *protogen.Plugin
	file     *protogen.File
	ordinary protogen.GoImportPath
	subdir   string

	deprecated bool

	// Current source code info path.
	scPath []int32
}

func (f *file) Run() {
	//nolint:errcheck
	f.deprecated = f.file.Desc.Options().(*descriptorpb.FileOptions).GetDeprecated()

	loc := f.LocationIn(wkt.FileDescriptorProto_Syntax)
	f.DetachedLeadingComments(loc)
	f.P("\n")
	f.P("// Code generated by protoc-gen-hyperpb. DO NOT EDIT.\n")
	f.P("// source: %s\n", f.file.Desc.Path())
	f.P("\n")
	loc = f.LocationIn(wkt.FileDescriptorProto_Package)
	f.DetachedLeadingComments(loc)
	f.P("\n")
	f.P("package %s\n\n", f.file.GoPackageName)

	imports := f.file.Desc.Imports()
	for i := range imports.Len() {
		f.Import(imports.Get(i))
	}
	f.GeneratedFile.Import(f.ordinary)

	f.Messages(wkt.FileDescriptorProto_Messages, f.file.Messages)

	_ = f.Finish()
}

func (f *file) Import(imp protoreflect.FileImport) {
	file, ok := f.pl.FilesByPath[imp.Path()]
	if !ok {
		return
	}

	path := file.GoImportPath
	path += "/"
	path += protogen.GoImportPath(f.subdir)

	if path == f.file.GoImportPath {
		return
	}

	// Generate imports for all dependencies, even if they are not
	// referenced, because other code and tools depend on having the
	// full transitive closure of protocol buffer types in the binary.
	f.GeneratedFile.Import(path)
	if !imp.IsPublic {
		return
	}

	// TODO: Public import forwards.
	f.Messages(wkt.FileDescriptorProto_Messages, f.file.Messages)
}

func (f *file) Messages(fd protoreflect.FieldDescriptor, mds []*protogen.Message) {
	for i, md := range mds {
		f.InList(fd, i, func() { f.Message(md) })
	}
}

func (f *file) Message(md *protogen.Message) {
	if md.Desc.IsMapEntry() {
		return
	}

	f.AnnotateSymbol(md.GoIdent.GoName, protogen.Annotation{
		Location: md.Location,
	})
	f.DefComments(md.GoIdent.GoName, f.Location())
	f.Deprecated(md.Desc)

	f.P("type %s struct { _ hyperpb.Message }\n\n", md.GoIdent.GoName)
	f.P("var t%s %s\n\n", md.GoIdent.GoName, exportType)
	f.P("func init() { t%s.Init(%q) }\n\n", md.GoIdent.GoName, md.Desc.FullName())

	f.P("// New%s allocates a new %s.\n", md.GoIdent.GoName, md.GoIdent.GoName)
	f.P("//\n")
	f.P("// s should usually be nil, but it may be used to re-use resources " +
		"between messages; see [hyperpb.Shared.NewMessage].\n")
	f.P("//\n")
	f.P("// Only this function can create valid values; new(%s) will not work.\n", md.GoIdent.GoName)
	f.P("func New%s(s *%s) *%s ",
		md.GoIdent.GoName,
		hyperpbShared,
		md.GoIdent.GoName,
	)
	f.Block("{", "}", func() {
		f.P("m := s.NewMessage(t%s.Get())\n", md.GoIdent.GoName)
		f.P("return (*%s)(%s(m))\n", md.GoIdent.GoName, unsafePointer)
	})
	f.P("\n\n")

	f.P("// Unmarshal is like [proto.Unmarshal], but permits hyperpb-specific\n")
	f.P("// tuning options to be set.\n")
	f.P("//\n")
	f.P("// See [hyperpb.Message.Unmarshal].\n")
	f.P("func (x *%s) Unmarshal(data []byte, options ...%s) error ", md.GoIdent.GoName, hyperpbOption)
	f.Block("{", "}", func() {
		f.P("return x.impl().Unmarshal(data, options...)\n")
	})
	f.P("\n\n")

	f.P("// Shared returns state shared by this message and its submessages.\n")
	f.P("func (x *%s) Shared() *%s ", md.GoIdent.GoName, hyperpbShared)
	f.Block("{", "}", func() {
		f.P("return x.impl().Shared()\n")
	})
	f.P("\n\n")

	for i, fd := range md.Fields {
		f.InList(wkt.MessageDescriptorProto_Fields, i, func() {
			switch {
			case fd.Desc.IsList():
				f.Repeated(md, fd)
			case fd.Desc.IsMap():
				return
			default:
				f.Singular(md, fd)
			}
		})
	}

	f.P("// ProtoReflect implements proto.Message.\n")
	f.P("func (x *%s) ProtoReflect() %s ", md.GoIdent.GoName, reflectMessage)
	f.Block("{", "}", func() {
		f.P("return %s(x)\n", exportReflect)
	})
	f.P("\n\n")

	f.P("func (*%s) HyperMessage(%s, *%s) {}\n\n",
		md.GoIdent.GoName,
		exportDNI,
		md.GoIdent.GoName,
	)

	f.P("func (x *%s) impl() *%s { return (*%[2]s)(%s(x)) }\n\n",
		md.GoIdent.GoName,
		hyperpbMessage,
		unsafePointer,
		md.GoIdent.GoName,
	)

	f.P("func (x *%s) unsafe() *%s { return (*%[2]s)(%s(x)) }\n\n",
		md.GoIdent.GoName,
		exportMessage,
		unsafePointer,
		md.GoIdent.GoName,
	)

	f.Messages(wkt.MessageDescriptorProto_Messages, md.Messages)
}

//nolint:goconst
func (f *file) Singular(md *protogen.Message, fd *protogen.Field) {
	var ty any
	var unsafeGetter string
	kind := fd.Desc.Kind()
	switch kind {
	case protoreflect.Int32Kind, protoreflect.Sint32Kind, protoreflect.Sfixed32Kind:
		ty = "int32"
		unsafeGetter = "GetInt32"
	case protoreflect.Uint32Kind, protoreflect.Fixed32Kind:
		ty = "uint32"
		unsafeGetter = "GetUint32"
	case protoreflect.Int64Kind, protoreflect.Sint64Kind, protoreflect.Sfixed64Kind:
		ty = "int64"
		unsafeGetter = "GetInt64"
	case protoreflect.Uint64Kind, protoreflect.Fixed64Kind:
		ty = "uint64"
		unsafeGetter = "GetUint64"

	case protoreflect.FloatKind:
		ty = "float32"
		unsafeGetter = "GetFloat32"
	case protoreflect.DoubleKind:
		ty = "float64"
		unsafeGetter = "GetFloat64"

	case protoreflect.StringKind:
		ty = "string"
		unsafeGetter = "GetString"
	case protoreflect.BytesKind:
		ty = "[]byte"
		unsafeGetter = "GetBytes"
	case protoreflect.BoolKind:
		ty = "bool"
		unsafeGetter = "GetBool"

	case protoreflect.EnumKind:
		ty = f.QualifiedGoIdent(fd.Enum.GoIdent)
		unsafeGetter = "GetEnum"
	case protoreflect.MessageKind, protoreflect.GroupKind:
		ty = "*" + f.QualifiedGoIdent(fd.Message.GoIdent)
		unsafeGetter = "GetMessage"
	}

	var ifNil string
	switch kind {
	case protoreflect.FloatKind:
		ifNil = fmt.Sprintf("%s(%#x)",
			f.QualifiedGoIdent(mathFloat32),
			math.Float32bits(float32(fd.Desc.Default().Float())))
	case protoreflect.DoubleKind:
		ifNil = fmt.Sprintf("%s(%#x)",
			f.QualifiedGoIdent(mathFloat64),
			math.Float64bits(fd.Desc.Default().Float()))

	case protoreflect.MessageKind, protoreflect.GroupKind:
		break

	case protoreflect.StringKind:
		ifNil = strconv.Quote(fd.Desc.Default().String())
	case protoreflect.BytesKind:
		ifNil = strconv.Quote(string(fd.Desc.Default().Bytes()))

	default:
		ifNil = fd.Desc.Default().String()
	}
	if ifNil != "" {
		ifNil = ", " + ifNil
	}

	getter, _ := fd.MethodName("Get")
	f.P("// %s extracts the value of %s.\n", getter, fd.Desc.FullName())
	f.P("//\n")
	f.DefComments("", f.Location())
	f.P("func (x *%s) %s() %s ",
		md.GoIdent.GoName,
		getter,
		ty,
	)
	f.Block("{", "}", func() {
		f.P("v := x.unsafe().%s(%d%s)\n",
			unsafeGetter,
			fd.Desc.Index(),
			ifNil,
		)

		if enum := fd.Enum; enum != nil {
			f.P("return %s(v)\n", ty)
			return
		}

		if message := fd.Message; message != nil {
			f.P("return (%s)(v)\n", ty)
			return
		}

		f.P("return v\n")
	})
	f.P("\n\n")

	if fd.Desc.HasOptionalKeyword() {
		hazzer, _ := fd.MethodName("Has")
		f.P("// %s checks whether %s is populated.\n", hazzer, fd.Desc.FullName())
		f.P("//\n")
		f.P("// See [%s.%s].\n", md.GoIdent.GoName, unsafeGetter)
		f.P("func (x *%s) %s() bool ",
			md.GoIdent.GoName,
			hazzer,
		)
		f.Block("{", "}", func() {
			f.P("return x.unsafe().Has(%d)\n",
				fd.Desc.Index(),
			)
		})
		f.P("\n\n")
	}
}

func (f *file) Repeated(md *protogen.Message, fd *protogen.Field) {
	var ty, unsafeGetter string
	kind := fd.Desc.Kind()
	switch kind {
	case protoreflect.Int32Kind:
		ty = "int32"
		unsafeGetter = "GetRepeatedInt32"
	case protoreflect.Sint32Kind:
		ty = "int32"
		unsafeGetter = "GetRepeatedSint32"
	case protoreflect.Sfixed32Kind:
		ty = "int32"
		unsafeGetter = "GetRepeatedSfixed32"

	case protoreflect.Uint32Kind:
		ty = "uint32"
		unsafeGetter = "GetRepeatedUint32"
	case protoreflect.Fixed32Kind:
		ty = "uint32"
		unsafeGetter = "GetRepeatedFixed32"

	case protoreflect.Int64Kind:
		ty = "int64"
		unsafeGetter = "GetRepeatedInt64"
	case protoreflect.Sint64Kind:
		ty = "int64"
		unsafeGetter = "GetRepeatedSint64"
	case protoreflect.Sfixed64Kind:
		ty = "int64"
		unsafeGetter = "GetRepeatedSfixed64"

	case protoreflect.Uint64Kind:
		ty = "uint64"
		unsafeGetter = "GetRepeatedUint64"
	case protoreflect.Fixed64Kind:
		ty = "uint64"
		unsafeGetter = "GetRepeatedFixed64"

	case protoreflect.FloatKind:
		ty = "float32"
		unsafeGetter = "GetRepeatedFloat32"
	case protoreflect.DoubleKind:
		ty = "float64"
		unsafeGetter = "GetRepeatedFloat64"

	case protoreflect.StringKind:
		ty = "string"
		unsafeGetter = "GetRepeatedString"
	case protoreflect.BytesKind:
		ty = "[]byte"
		unsafeGetter = "GetRepeatedBytes"
	case protoreflect.BoolKind:
		ty = "bool"
		unsafeGetter = "GetRepeatedBool"

	case protoreflect.EnumKind:
		ty = f.QualifiedGoIdent(fd.Enum.GoIdent)
		unsafeGetter = "GetRepeatedEnum"

	case protoreflect.MessageKind, protoreflect.GroupKind:
		ty = "*" + f.QualifiedGoIdent(fd.Message.GoIdent)
		unsafeGetter = "GetRepeatedMessage"
	}

	getter, _ := fd.MethodName("Get")
	f.P("// %s extracts the value of %s.\n", getter, fd.Desc.FullName())
	f.P("//\n")
	f.DefComments("", f.Location())
	f.P("func (x *%s) %s() %s[%s] ",
		md.GoIdent.GoName,
		getter,
		hyperpbList,
		ty,
	)
	f.Block("{", "}", func() {
		f.P("v := x.unsafe().%s(%d)\n",
			unsafeGetter,
			fd.Desc.Index(),
		)

		if enum := fd.Enum; enum != nil {
			f.P("return %s[%s](v)\n", exportCastEnum, ty)
			return
		}

		if message := fd.Message; message != nil {
			f.P("return %s[%s](v)\n", exportCastMessage, ty)
			return
		}

		f.P("return v\n")
	})
	f.P("\n\n")
}

// In runs a callback in the context of a particular field descriptor, necessary
// for source code info lookups to work correctly.
func (f *file) In(fd protoreflect.FieldDescriptor, body func()) {
	f.scPath = append(f.scPath, int32(fd.Number()))
	body()
	f.scPath = f.scPath[:len(f.scPath)-1]
}

// InList is like In, but for recursing into a repeated field.
func (f *file) InList(fd protoreflect.FieldDescriptor, n int, body func()) {
	f.scPath = append(f.scPath, int32(fd.Number()), int32(n))
	body()
	f.scPath = f.scPath[:len(f.scPath)-2]
}

// Location returns the source location for the current position.
func (f *file) Location() protoreflect.SourceLocation {
	return f.file.Desc.SourceLocations().ByPath(f.scPath)
}

// LocationIn returns the source location for a field of the current position.
func (f *file) LocationIn(fd protoreflect.FieldDescriptor) protoreflect.SourceLocation {
	return f.file.Desc.SourceLocations().ByPath(append(f.scPath, int32(fd.Number())))
}

func (f *file) DefComments(name string, loc protoreflect.SourceLocation) {
	if c := loc.LeadingComments; c != "" {
		f.P("%v", protogen.Comments(c))
		return
	}

	if name == "" {
		name = "This definition"
	}

	f.P("// %v is undocumented in the .proto file.\n", name)
}

// Deprecated prints deprecation warnings.
func (f *file) Deprecated(node interface {
	FullName() protoreflect.FullName
	Options() proto.Message
},
) {
	if f.deprecated {
		f.P("//\n// Deprecated: the file %s is marked as deprecated.", f.file.Desc.Path())
		return
	}

	//nolint:errcheck
	options := node.Options().(interface{ GetDeprecated() bool })
	if options.GetDeprecated() {
		f.P("//\n// Deprecated: %s is marked as deprecated.", node.FullName())
	}
}

func (f *file) DetachedLeadingComments(loc protoreflect.SourceLocation) {
	for _, c := range loc.LeadingDetachedComments {
		f.P("%v\n", protogen.Comments(c))
	}

	if c := loc.LeadingComments; c != "" {
		f.P("%v\n", protogen.Comments(c))
	}
}
