// Copyright 2025 Buf Technologies, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by buf.build/go/hyperpb/internal/tools/hyperstencil. DO NOT EDIT.

//go:build amd64

package varint

import (
	"buf.build/go/hyperpb/internal/debug"
	"buf.build/go/hyperpb/internal/tdp"
	"buf.build/go/hyperpb/internal/tdp/vm/internal/state"
	"buf.build/go/hyperpb/internal/xunsafe"
	"buf.build/go/hyperpb/internal/xunsafe/layout"
	"math/bits"
	"runtime"
	"simd/archsimd"
)

//go:nosplit
func AVX32(p1 state.P1, p2 state.P2) (state.P1, state.P2, uint64) {
	_ = AVX[uint32]
	long := layout.Size[uint32]() == 8

	start := p1.PtrAddr
	var x uint64

	{

		if p1.Len() < 16 {
			return ScalarSplit(p1, p2)
		}

		data := archsimd.LoadUint8x16(xunsafe.Cast[[16]uint8](p1.Ptr()))
		p1.Log(p2, "varint-avx", "data: %b", data)

		signs := archsimd.Mask8x16(data.AsInt8x16()).ToBits()

		n := bits.TrailingZeros16(^signs)
		len := bits.TrailingZeros16(^signs) + 1

		data = data.And(truncMasks[n])
		p1.Log(p2, "varint-avx", "len: %d, trunc: %b", len, data)

		var lo, hi archsimd.Uint16x8
		if long {
			lo, hi = split8to16(data)
		} else {
			lo = data.ExtendLo8ToUint16()
		}
		p1.Log(p2, "varint-avx", "lo: %b, hi: %b", lo, hi)

		lo = lo.Mul(mulShift)
		if long {
			hi = hi.Mul(mulShift)
		}
		p1.Log(p2, "varint-avx", "lo: %b, hi: %b", lo, hi)

		shuf0 := lo.AsUint8x16().PermuteOrZero(shuffles[0])
		shuf1 := lo.AsUint8x16().PermuteOrZero(shuffles[1])
		p1.Log(p2, "varint-avx", "0: %b, 1: %b", shuf0, shuf1)
		or := shuf0.Or(shuf1)

		if long {
			shuf2 := hi.AsUint8x16().PermuteOrZero(shuffles[2])
			shuf3 := hi.AsUint8x16().PermuteOrZero(shuffles[3])
			p1.Log(p2, "varint-avx", "2: %b, 3: %b", shuf2, shuf3)
			or = or.Or(shuf2).Or(shuf3)
		}

		p1.Log(p2, "varint-avx", "or: %b", or)
		x = or.AsUint64x2().GetElem(0)
		p1.Log(p2, "varint-avx", "out: %d, %b", x, x)

		if len >= 10 && (len > 10 || data.GetElem(9) > 1) {
			goto fail
		}

		p1.PtrAddr = p1.PtrAddr.Add(len)
	}

	if debug.Enabled {
		len := int(p1.PtrAddr - start)
		p1.Log(p2, "varint-avx", "%d:%#x (%d bytes)", x, x, len)
		runtime.GC()
	}

	return p1, p2, x

fail:
	p1.Fail(p2, tdp.ErrorTruncated)
	for {
	}
}

//go:nosplit
func AVX64(p1 state.P1, p2 state.P2) (state.P1, state.P2, uint64) {
	_ = AVX[uint64]
	long := layout.Size[uint64]() == 8

	start := p1.PtrAddr
	var x uint64

	{

		if p1.Len() < 16 {
			return ScalarSplit(p1, p2)
		}

		data := archsimd.LoadUint8x16(xunsafe.Cast[[16]uint8](p1.Ptr()))
		p1.Log(p2, "varint-avx", "data: %b", data)

		signs := archsimd.Mask8x16(data.AsInt8x16()).ToBits()

		n := bits.TrailingZeros16(^signs)
		len := bits.TrailingZeros16(^signs) + 1

		data = data.And(truncMasks[n])
		p1.Log(p2, "varint-avx", "len: %d, trunc: %b", len, data)

		var lo, hi archsimd.Uint16x8
		if long {
			lo, hi = split8to16(data)
		} else {
			lo = data.ExtendLo8ToUint16()
		}
		p1.Log(p2, "varint-avx", "lo: %b, hi: %b", lo, hi)

		lo = lo.Mul(mulShift)
		if long {
			hi = hi.Mul(mulShift)
		}
		p1.Log(p2, "varint-avx", "lo: %b, hi: %b", lo, hi)

		shuf0 := lo.AsUint8x16().PermuteOrZero(shuffles[0])
		shuf1 := lo.AsUint8x16().PermuteOrZero(shuffles[1])
		p1.Log(p2, "varint-avx", "0: %b, 1: %b", shuf0, shuf1)
		or := shuf0.Or(shuf1)

		if long {
			shuf2 := hi.AsUint8x16().PermuteOrZero(shuffles[2])
			shuf3 := hi.AsUint8x16().PermuteOrZero(shuffles[3])
			p1.Log(p2, "varint-avx", "2: %b, 3: %b", shuf2, shuf3)
			or = or.Or(shuf2).Or(shuf3)
		}

		p1.Log(p2, "varint-avx", "or: %b", or)
		x = or.AsUint64x2().GetElem(0)
		p1.Log(p2, "varint-avx", "out: %d, %b", x, x)

		if len >= 10 && (len > 10 || data.GetElem(9) > 1) {
			goto fail
		}

		p1.PtrAddr = p1.PtrAddr.Add(len)
	}

	if debug.Enabled {
		len := int(p1.PtrAddr - start)
		p1.Log(p2, "varint-avx", "%d:%#x (%d bytes)", x, x, len)
		runtime.GC()
	}

	return p1, p2, x

fail:
	p1.Fail(p2, tdp.ErrorTruncated)
	for {
	}
}
