// Copyright 2025 Buf Technologies, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Package constraint defines an interface satisfied by any pointer to a gencode
// type.
package gencode

import (
	"google.golang.org/protobuf/proto"
)

// DoNotImplement indicates that something should not be implemented.
type DoNotImplement struct{ _ struct{} }

// Message is a pointer to a type generated by protoc-gen-hyperpb.
type Message[M any] interface {
	proto.Message
	HyperMessage(DoNotImplement, *M)
}
