name: Buf CI
on:
  push:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]
  delete:
permissions:
  contents: read
  pull-requests: write
jobs:
  buf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bufbuild/buf-action@v1
        with:
          version: 1.50.0 # Keep in sync with Makefile BUF_VERSION
          format: false # Turn off format, since most proto definitions are for testing
          breaking: false # Temporarily turn-off breaking, since we are splitting up the modules
          token: ${{ secrets.BUF_TOKEN }}
